steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - services/rag-api/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/zheight-services/rag-api:v2.0
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/zheight-services/rag-api:v2.0
